import os
from dotenv import load_dotenv

load_dotenv()

# LLM / Embeddings
AZURE_ENDPOINT = os.getenv("AZURE_ENDPOINT")
AZURE_API_KEY = os.getenv("AZURE_API_KEY")

EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIM = 1536               
LLM_MODEL = "gpt-4.1-mini"

NER_MODEL = "Jean-Baptiste/roberta-large-ner-english"
HEADERS_EMBEDDING_MODEL = "sentence-transformers/all-mpnet-base-v2"               


# Qdrant (vector store)
QDRANT_URL        = os.getenv("QDRANT_URL")        
QDRANT_API_KEY    = os.getenv("QDRANT_API_KEY")
QDRANT_COLLECTION = "cv_chunks"


# Neo4j (graph store)
NEO4J_URI      = os.getenv("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USER     = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "")
NEO4J_DATABASE = os.getenv("NEO4J_DATABASE", "neo4j")


# Pipeline knobs
NUM_EXTRA_QUERIES = 2        
MAX_CVS           = 5

CHUNKS_PER_QUERY_LLM     = 10
CHUNKS_PER_QUERY_DOCLING = 20

RETRIEVAL_MODE = "Hybrid"   
RRF_K          = 60 

GRAPH_MAX_RESULTS = 50      # max rows returned from a single Neo4j query


# Chunking section normalisation
KNOWN_SECTIONS = [
    # Personal / Introduction
    "PROFILE", "ABOUT ME", "ABOUT", "PERSONAL PROFILE", "PERSONAL STATEMENT",
    "PROFESSIONAL PROFILE", "PROFESSIONAL SUMMARY", "CAREER PROFILE",
    "SUMMARY", "EXECUTIVE SUMMARY", "CAREER SUMMARY", "CAREER OBJECTIVE",
    "OBJECTIVE", "PROFESSIONAL OBJECTIVE", "CAREER GOAL", "GOAL",
    "INTRODUCTION", "OVERVIEW", "BIO", "BIOGRAPHY",

    # Experience
    "EXPERIENCE", "WORK EXPERIENCE", "PROFESSIONAL EXPERIENCE",
    "EMPLOYMENT HISTORY", "EMPLOYMENT", "WORK HISTORY",
    "CAREER HISTORY", "CAREER EXPERIENCE", "RELEVANT EXPERIENCE",
    "INDUSTRY EXPERIENCE", "FIELD EXPERIENCE", "INTERNSHIP EXPERIENCE",
    "INTERNSHIP", "INTERNSHIPS", "VOLUNTEER EXPERIENCE", "VOLUNTEERING",
    "COMMUNITY SERVICE", "SERVICE", "FREELANCE EXPERIENCE", "FREELANCE WORK",
    "CONSULTING EXPERIENCE", "CONTRACT WORK", "TRAINING & INTERNSHIP"

    # Education
    "EDUCATION", "ACADEMIC BACKGROUND", "ACADEMIC HISTORY",
    "EDUCATIONAL BACKGROUND", "EDUCATIONAL QUALIFICATIONS",
    "QUALIFICATIONS", "ACADEMIC QUALIFICATIONS", "DEGREES",
    "ACADEMIC ACHIEVEMENTS", "ACADEMIC TRAINING", "SCHOOLING",

    # Skills
    "SKILLS", "TECHNICAL SKILLS", "CORE SKILLS", "KEY SKILLS",
    "PROFESSIONAL SKILLS", "SOFT SKILLS", "HARD SKILLS",
    "TRANSFERABLE SKILLS", "INTERPERSONAL SKILLS", "COMMUNICATION SKILLS",
    "COMPETENCIES", "CORE COMPETENCIES", "KEY COMPETENCIES",
    "TECHNICAL COMPETENCIES", "AREAS OF EXPERTISE", "EXPERTISE",
    "SPECIALIZATIONS", "SPECIALTIES", "ABILITIES", "STRENGTHS",
    "CAPABILITIES", "SKILL SET", "TECHNICAL PROFICIENCIES", "PROFICIENCIES",
    "TOOLS & TECHNOLOGIES", "TOOLS AND TECHNOLOGIES", "TECHNOLOGIES",
    "TECHNOLOGY STACK", "TECH STACK",

    # Projects
    "PROJECTS", "PROJECT EXPERIENCE", "KEY PROJECTS", "NOTABLE PROJECTS",
    "SELECTED PROJECTS", "PERSONAL PROJECTS", "ACADEMIC PROJECTS",
    "RESEARCH PROJECTS", "PROFESSIONAL PROJECTS", "SIDE PROJECTS",
    "PORTFOLIO", "WORK SAMPLES", "CASE STUDIES",

    # Training & Courses
    "TRAINING", "TRAINING & DEVELOPMENT", "TRAINING AND DEVELOPMENT",
    "COURSES", "COURSEWORK", "RELEVANT COURSEWORK", "ONLINE COURSES",
    "PROFESSIONAL DEVELOPMENT", "PROFESSIONAL TRAINING",
    "WORKSHOPS", "SEMINARS", "BOOTCAMPS", "BOOTCAMP",

    # Certifications & Licenses
    "CERTIFICATIONS", "CERTIFICATION", "CERTIFICATES", "CERTIFICATE",
    "PROFESSIONAL CERTIFICATIONS", "TECHNICAL CERTIFICATIONS",
    "LICENSES", "LICENSE", "LICENSES & CERTIFICATIONS",
    "ACCREDITATIONS", "CREDENTIALS", "PROFESSIONAL CREDENTIALS",
    "DESIGNATIONS", "PROFESSIONAL LICENSES",

    # Languages
    "LANGUAGES", "LANGUAGE SKILLS", "SPOKEN LANGUAGES",
    "FOREIGN LANGUAGES", "LANGUAGE PROFICIENCY", "LINGUISTIC SKILLS",

    # Publications & Research
    "PUBLICATIONS", "PUBLISHED WORKS", "RESEARCH",
    "RESEARCH EXPERIENCE", "RESEARCH & PUBLICATIONS",
    "PAPERS", "JOURNAL ARTICLES", "CONFERENCE PAPERS",
    "PRESENTATIONS", "CONFERENCE PRESENTATIONS", "TALKS",
    "POSTERS", "THESIS", "DISSERTATION",

    # Awards & Recognition
    "AWARDS", "HONORS", "HONOURS", "AWARDS & HONORS",
    "AWARDS & HONOURS", "ACHIEVEMENTS", "ACCOMPLISHMENTS",
    "RECOGNITION", "NOTABLE ACHIEVEMENTS", "KEY ACHIEVEMENTS",
    "DISTINCTIONS", "SCHOLARSHIPS", "FELLOWSHIPS",
    "GRANTS", "PRIZES",

    # Leadership & Activities
    "LEADERSHIP", "LEADERSHIP EXPERIENCE", "LEADERSHIP & ACTIVITIES",
    "EXTRACURRICULAR ACTIVITIES", "EXTRACURRICULAR",
    "ACTIVITIES", "CLUBS & ACTIVITIES", "STUDENT ACTIVITIES",
    "ORGANIZATIONS", "PROFESSIONAL ORGANIZATIONS",
    "AFFILIATIONS", "PROFESSIONAL AFFILIATIONS",
    "MEMBERSHIPS", "PROFESSIONAL MEMBERSHIPS",
    "ASSOCIATIONS", "PROFESSIONAL ASSOCIATIONS",

    # Volunteering / Social
    "VOLUNTEER WORK", "VOLUNTEERING", "COMMUNITY INVOLVEMENT",
    "CIVIC ENGAGEMENT", "SOCIAL IMPACT", "SOCIAL WORK",
    "NON-PROFIT EXPERIENCE", "NGO EXPERIENCE",

    # References
    "REFERENCES", "PROFESSIONAL REFERENCES", "REFEREES",
    "REFERENCES AVAILABLE UPON REQUEST",

    # Technical / Engineering / IT specific
    "PROGRAMMING LANGUAGES", "FRAMEWORKS", "LIBRARIES",
    "DATABASES", "OPERATING SYSTEMS", "PLATFORMS",
    "DEVOPS", "CLOUD PLATFORMS", "SOFTWARE",
    "HARDWARE", "LABORATORY SKILLS", "LAB SKILLS",

    # Creative / Design specific
    "DESIGN SKILLS", "CREATIVE SKILLS", "CREATIVE PORTFOLIO",
    "EXHIBITIONS", "EXHIBITIONS & SHOWS", "COLLECTIONS",
    "COMMISSIONS", "ART INSTALLATIONS",

    # Medical / Healthcare specific
    "CLINICAL EXPERIENCE", "CLINICAL ROTATIONS", "ROTATIONS",
    "MEDICAL TRAINING", "RESIDENCY", "FELLOWSHIPS",
    "PROCEDURES", "CLINICAL SKILLS",

    # Legal specific
    "BAR ADMISSIONS", "COURT ADMISSIONS", "LEGAL EXPERIENCE",
    "CASES", "LEGAL PUBLICATIONS",

    # Academic / Teaching specific
    "TEACHING EXPERIENCE", "TEACHING", "COURSES TAUGHT",
    "ACADEMIC APPOINTMENTS", "APPOINTMENTS",
    "ACADEMIC SERVICE", "GRANTS & FUNDING",
    "EDITORIAL ROLES", "REVIEWING",

    # Business / Finance specific
    "BUSINESS DEVELOPMENT", "KEY ACCOUNTS", "CLIENTS",
    "PORTFOLIO MANAGEMENT", "FINANCIAL SKILLS",

    # Military / Government
    "MILITARY SERVICE", "MILITARY EXPERIENCE",
    "SECURITY CLEARANCE", "CLEARANCES", "MILITARY STATUS",

    # Miscellaneous
    "INTERESTS", "HOBBIES", "PERSONAL INTERESTS",
    "HOBBIES & INTERESTS", "PASSIONS",
    "ADDITIONAL INFORMATION", "ADDITIONAL SKILLS",
    "OTHER INFORMATION", "OTHER SKILLS", "OTHER",
    "CONTACT", "CONTACT INFORMATION", "PERSONAL DETAILS",
    "PERSONAL INFORMATION",
]














# CEREBRAS_API_KEY = os.getenv("CEREBRAS_API_KEY")


# EMBEDDING_MODEL = "intfloat/e5-large"         # "BAAI/bge-base-en-v1.5"
# LLM_MODEL = "gpt-oss-120b"
# EMBEDDING_DIM = 1024                          # 768